name = "CEF"
uuid = "a0ebe571-4eea-4bd0-90ac-e9ca257b9c48"
authors = ["J. A. Hern√°ndez"]
version = "0.1.0-DEV"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataFramesMeta = "1313f7d8-7da2-5740-9ea0-a2ca25f37964"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
OffsetArrays = "6fe1bfb0-de20-5000-8ca7-80f57d26f881"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Trapz = "592b5752-818d-11e9-1e9a-2b8ca4a44cd1"

[compat]
DataFrames = "1.7.0"
DataFramesMeta = "0.15.4"
LinearAlgebra = "1.11.0"
OffsetArrays = "1.15.0"
Printf = "1.11.0"
StaticArrays = "1.9.13"
Statistics = "1.11.1"
Trapz = "2.0.3"
julia = "1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
